spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/malldb
    username: malldbuser
    password: malldbuser
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 스키마 자동 생성
    show-sql: true # SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true # SQL pretty print
